<?php
/**
 * Created by PhpStorm.
 * User: 18723
 * Date: 2018/5/21
 * Time: 9:29
 * 对应数据表 www_param 对数据表的操作
 */
namespace app\admin\model;

use think\Model;

//参数操作
class Param extends Model{
    //模型初始化
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    //增加参数操作 需要批量增加 前端返回list 遍历
    public function addParam($date)
    {
        /*
         * 逻辑 1判断参数名是否重复 重复则返回false 2不重复则向数据库添加数据并保存
         */
        $list = $date['paramname'];
        $typeid = $date['typeid'];
//        var_dump($list,$typeid);die;
        foreach($list as $key=>$value) {
            $name = Param::where('paramname',$value)->find();
            if(!empty($name)) {
                return false;
            } else {
                $param = new Param();
                $param->paramname = $value;
                $param->typeid = $typeid;
                $param->save();
            }
        }
        return $param;
    }

    //修改参数操作
    public function editParam($date)
    {
        /*
        * 逻辑：1根据id找到该数据 不存在返回false 2存在该数据 将获取的参数更新
        */
        $param = Param::where('id',$date['id'])->find();
        if(empty($param)) {
            return false;
        } else {
            $param->paramname = $date['paramname'];
            $param->save();
            return $param;
        }
    }

    //删除参数操作
    public function delParam($paramid)
    {
        /*
         * 逻辑：1获取id 2数据表找到数据 delete 3判断成功返回true 否则false
         */
        $param = Param::where('id', $paramid)->delete();
        if($param !== false) {
            return 1;
        } else {
            return null;
        }
    }

    //按键值名删除值
    public function array_remove($data,$key) {
        if(!array_key_exists($key, $data)){
            return $data;
        }
        $keys = array_keys($data);
        $index = array_search($key, $keys);
        if($index !== FALSE){
            array_splice($data, $index, 1);
        }
        return $data;
    }
}